
import React from 'react';
import CodeBlock from '../../components/CodeBlock';
import { DocPage, DocHeader, PageNav } from '../../components/DocLayout';

export default function StructuredOutput() {
  return (
    <DocPage>

      <DocHeader
        breadcrumbs={[
          { label: 'Home', href: '/' },
          { label: 'LangChain', href: '/langchain/structured' },
          { label: 'StructuredOutput' }
        ]}
        title="Structured Output & Output Parsers"
        readTime="25 min read"
        level="Beginner"
        updated="September 2026"
      />

      {/* Introduction */}
      <section>
        <h2>Handling LLM Output</h2>

        <p>
          Previously, we discussed how to provide input or prompts to LLMs.
          Now, we will discuss how to handle the output generated by LLMs.
        </p>

        <p>
          In LangChain, <strong>structured output</strong> refers to the
          practice of having language models return responses in a
          well-defined data format such as JSON instead of free-form text.
          This makes the model output easier to parse, validate, store,
          and use inside applications.
        </p>
      </section>


        <div className="image-wrapper">
        <img
          src="/images/st1.PNG.png"
          alt="Structured Output"
          style={{
            width: '100%',
            maxWidth: '650px',
            height: 'auto',
            display: 'block',
            margin: '20px auto',
            borderRadius: '8px'
          }}
        />
      </div>

 


      {/* Why Structured Output */}
      <section>
        <h2>Why do we need Structured Output?</h2>

        <p>
          LLMs normally generate human-readable text. However, applications
          often need the information in a specific format so that it can be
          processed by programs.
        </p>

        <ol>
          <li>
            <strong>Data Extraction:</strong> For example, we give a resume
            containing text to an LLM. The LLM can extract information such
            as the candidate's name, previous job, skills, etc. in JSON
            format, which can then be stored inside a database.
          </li>

          <li>
            <strong>API Building:</strong> Suppose products on Amazon
            contain customer reviews. An LLM can extract information such
            as topic, pros, and cons in JSON format. We can then create an
            API through which users can access this structured data.
          </li>

          <li>
            <strong>Agents:</strong> An agent may use a tool to perform
            mathematical operations. The LLM may receive information in
            textual form, but we need to convert that information into
            structured numerical values before sending it to a calculator
            tool.
          </li>
        </ol>

        <div className="note">
          <strong>In short:</strong> The output generated by an LLM needs to
          be converted into a structured format so that the data can be
          stored in a database, used by an API, passed to tools, or handled
          by other parts of an application.
        </div>
      </section>


      {/* Ways to get Structured Output */}
      <section>
        <h2>Ways to get Structured Output</h2>

        <p>
          There are mainly two ways to obtain structured output from an LLM
          in LangChain:
        </p>

          <div className="image-wrapper">
        <img
          src="/images/st2.PNG.png"
          alt="Structured Output Methods"
          style={{
            width: '100%',
            maxWidth: '650px',
            height: 'auto',
            display: 'block',
            margin: '20px auto',
            borderRadius: '8px'
          }}
        />
      </div>

        <ul>
          <li>
            Some LLMs can generate structured output themselves. For these
            models, LangChain provides the
            <strong> with_structured_output()</strong> function.
          </li>

          <li>
            Some LLMs cannot directly generate structured output. In that
            case, we can use <strong>Output Parsers</strong>.
          </li>
        </ul>
      </section>


      {/* with_structured_output */}
      <section>
        <h2>with_structured_output()</h2>
          <div className="image-wrapper">
        <img
          src="/images/st3.PNG.png"
          alt="with_structured_output()"
          style={{
            width: '100%',
            maxWidth: '650px',
            height: 'auto',
            display: 'block',
            margin: '20px auto',
            borderRadius: '8px'
          }}
        />
      </div>

        <p>
          <strong>with_structured_output()</strong> allows us to define the
          expected format of the LLM response while invoking the model.
        </p>

        <p>
          The schema tells the model what fields should be returned and what
          type of information each field should contain.
        </p>

        <h3>Three ways to define the schema</h3>

        <ol>
          <li>TypedDict</li>
          <li>Pydantic</li>
          <li>JSON Schema</li>
        </ol>
      </section>


      {/* TypedDict */}
      <section>
        <h3>1. TypedDict</h3>
          <div className="image-wrapper">
        <img
          src="/images/st4.PNG.png"
          alt="TypedDict"
          style={{
            width: '100%',
            maxWidth: '650px',
            height: 'auto',
            display: 'block',
            margin: '20px auto',
            borderRadius: '8px'
          }}
        />
      </div>

        <p>
          <strong>TypedDict</strong> is used to define the expected structure
          of a Python dictionary using type hints.
        </p>

        <CodeBlock language="python">
{`from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from typing import TypedDict, Annotated, Optional, Literal

load_dotenv()

model = ChatOpenAI()

# Schema
class Review(TypedDict):

    key_themes: Annotated[
        list[str],
        "Write down all the key themes discussed in the review in a list"
    ]

    summary: Annotated[
        str,
        "A brief summary of the review"
    ]

    sentiment: Annotated[
        Literal["pos", "neg"],
        "Return sentiment of the review either negative, positive or neutral"
    ]

    pros: Annotated[
        Optional[list[str]],
        "Write down all the pros inside a list"
    ]

    cons: Annotated[
        Optional[list[str]],
        "Write down all the cons inside a list"
    ]

    name: Annotated[
        Optional[str],
        "Write the name of the reviewer"
    ]


# Convert the normal model into a structured-output model
structured_model = model.with_structured_output(Review)


result = structured_model.invoke("""
I recently upgraded to the Samsung Galaxy S24 Ultra, and I must say,
it’s an absolute powerhouse! The Snapdragon 8 Gen 3 processor makes
everything lightning fast—whether I’m gaming, multitasking, or editing
photos. The 5000mAh battery easily lasts a full day even with heavy use,
and the 45W fast charging is a lifesaver.

The S-Pen integration is a great touch for note-taking and quick sketches,
though I don't use it often. What really blew me away is the 200MP camera—
the night mode is stunning, capturing crisp, vibrant images even in low
light. Zooming up to 100x actually works well for distant objects, but
anything beyond 30x loses quality.

However, the weight and size make it a bit uncomfortable for one-handed
use. Also, Samsung’s One UI still comes with bloatware. The $1,300 price
tag is also a hard pill to swallow.

Pros:
- Insanely powerful processor
- Stunning 200MP camera
- Long battery life with fast charging
- S-Pen support is unique and useful

Review by Nitish Singh
""")


print(result['name'])`}
        </CodeBlock>

        <p>
          Here, the <strong>Review</strong> schema defines exactly what
          information we want from the review.
        </p>
      </section>


      {/* Pydantic */}
      <section>
        <h3>2. Pydantic</h3>

        <p>
          <strong>Pydantic</strong> is a data validation and data parsing
          library for Python. It ensures that the data we work with is
          correct, structured, and type-safe.
        </p>

        <CodeBlock language="python">
{`from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from typing import Optional, Literal
from pydantic import BaseModel, Field

load_dotenv()

model = ChatOpenAI()

# Schema
class Review(BaseModel):

    key_themes: list[str] = Field(
        description="Write down all the key themes discussed in the review in a list"
    )

    summary: str = Field(
        description="A brief summary of the review"
    )

    sentiment: Literal["pos", "neg"] = Field(
        description="Return sentiment of the review either negative, positive or neutral"
    )

    pros: Optional[list[str]] = Field(
        default=None,
        description="Write down all the pros inside a list"
    )

    cons: Optional[list[str]] = Field(
        default=None,
        description="Write down all the cons inside a list"
    )

    name: Optional[str] = Field(
        default=None,
        description="Write the name of the reviewer"
    )


# Convert model to structured-output model
structured_model = model.with_structured_output(Review)


result = structured_model.invoke("""
I recently upgraded to the Samsung Galaxy S24 Ultra, and I must say,
it’s an absolute powerhouse! The Snapdragon 8 Gen 3 processor makes
everything lightning fast.

The 5000mAh battery easily lasts a full day even with heavy use,
and the 45W fast charging is a lifesaver.

The 200MP camera is excellent, especially in low light. However,
the phone is heavy and expensive.

Pros:
- Powerful processor
- Excellent camera
- Long battery life
- S-Pen support

Review by Nitish Singh
""")


print(result)`}
        </CodeBlock>

        <p>
          Pydantic is useful when we want the returned data to follow a
          clearly defined Python model and want validation of the fields.
        </p>
      </section>


      {/* JSON Schema */}
      <section>
        <h3>3. JSON Schema</h3>

        <p>
          <strong>JSON Schema</strong> is useful when the structure needs to
          be described in a standard JSON-based format. It is especially
          useful when working across multiple programming languages.
        </p>

        <CodeBlock language="python">
{`from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

model = ChatOpenAI()

# JSON Schema
json_schema = {
    "title": "Review",

    "type": "object",

    "properties": {

        "key_themes": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description":
                "Write down all the key themes discussed in the review in a list"
        },

        "summary": {
            "type": "string",
            "description":
                "A brief summary of the review"
        },

        "sentiment": {
            "type": "string",
            "enum": ["pos", "neg"],
            "description":
                "Return sentiment of the review either negative, positive or neutral"
        },

        "pros": {
            "type": ["array", "null"],
            "items": {
                "type": "string"
            },
            "description":
                "Write down all the pros inside a list"
        },

        "cons": {
            "type": ["array", "null"],
            "items": {
                "type": "string"
            },
            "description":
                "Write down all the cons inside a list"
        },

        "name": {
            "type": ["string", "null"],
            "description":
                "Write the name of the reviewer"
        }
    },

    "required": [
        "key_themes",
        "summary",
        "sentiment"
    ]
}


structured_model = model.with_structured_output(json_schema)


result = structured_model.invoke("""
I recently upgraded to the Samsung Galaxy S24 Ultra.

The processor is extremely powerful and the battery lasts a full day.
The camera produces excellent images, especially in low light.

However, the phone is heavy and expensive.

Pros:
- Powerful processor
- Excellent camera
- Long battery life
- S-Pen support

Review by Nitish Singh
""")


print(result)`}
        </CodeBlock>

        <p>
          JSON Schema provides a language-independent way of describing the
          structure that the LLM should return.
        </p>
      </section>

        <div className="image-wrapper">
        <img
          src="/images/st5.PNG"
          alt="Structured Output "
          style={{
            width: '100%',
            maxWidth: '650px',
            height: 'auto',
            display: 'block',
            margin: '20px auto',
            borderRadius: '8px'
          }}
        />
      </div>


      {/* Output Parser */}
      <section>
        <h2>Output Parser</h2>

        <p>
          Output Parsers in LangChain help convert raw LLM responses into
          structured formats such as JSON, CSV, Pydantic models, and more.
          They help provide consistency, validation, and easier integration
          with applications.
        </p>

        <h3>Types of Output Parsers</h3>

        <ol>
          <li>StrOutputParser</li>
          <li>JSONOutputParser</li>
          <li>StructuredOutputParser</li>
          <li>PydanticOutputParser</li>
        </ol>
      </section>


      {/* StrOutputParser */}
      <section>
        <h3>1. StrOutputParser</h3>

        <p>
          <strong>StrOutputParser</strong> is the simplest output parser in
          LangChain. It parses the output of an LLM and returns it as a
          plain string.
        </p>

        <p>
          For example, we can create an LLM that first generates a detailed
          report on a topic and then use another prompt to create a
          five-line summary of that report.
        </p>

        <CodeBlock language="python">
{`from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

load_dotenv()

model = ChatOpenAI()


# 1st prompt -> detailed report
template1 = PromptTemplate(
    template='Write a detailed report on {topic}',
    input_variables=['topic']
)


# 2nd prompt -> summary
template2 = PromptTemplate(
    template='Write a 5 line summary on the following text. \\n {text}',
    input_variables=['text']
)


# Parser
parser = StrOutputParser()


# Chain
chain = template1 | model | parser | template2 | model | parser


result = chain.invoke({
    'topic': 'black hole'
})


print(result)`}
        </CodeBlock>

        <div className="note">
          <strong>Key Point:</strong> StrOutputParser is useful when the
          required output is simply a normal text string.
        </div>
      </section>


      {/* JSONOutputParser */}
      <section>
        <h3>2. JSONOutputParser</h3>

        <p>
          <strong>JSONOutputParser</strong> helps convert the LLM response
          into JSON format.
        </p>

        <CodeBlock language="python">
{`from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser

load_dotenv()


# Define the model
llm = HuggingFaceEndpoint(
    repo_id="google/gemma-2-2b-it",
    task="text-generation"
)


model = ChatHuggingFace(llm=llm)


# Create JSON parser
parser = JsonOutputParser()


template = PromptTemplate(
    template='Give me 5 facts about {topic} \\n {format_instruction}',

    input_variables=['topic'],

    partial_variables={
        'format_instruction':
            parser.get_format_instructions()
    }
)


# Create chain
chain = template | model | parser


result = chain.invoke({
    'topic': 'black hole'
})


print(result)`}
        </CodeBlock>
      </section>


      {/* StructuredOutputParser */}
      <section>
        <h3>3. StructuredOutputParser</h3>

        <p>
          <strong>StructuredOutputParser</strong> is an output parser in
          LangChain that helps extract data from LLM responses based on
          predefined field schemas.
        </p>

        <p>
          We define a list of fields that the model should return. This
          ensures that the output follows a predefined structure.
        </p>

        <CodeBlock language="python">
{`from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain.output_parsers import StructuredOutputParser, ResponseSchema

load_dotenv()


# Define the model
llm = HuggingFaceEndpoint(
    repo_id="google/gemma-2-2b-it",
    task="text-generation"
)


model = ChatHuggingFace(llm=llm)


# Define the expected fields
schema = [

    ResponseSchema(
        name='fact_1',
        description='Fact 1 about the topic'
    ),

    ResponseSchema(
        name='fact_2',
        description='Fact 2 about the topic'
    ),

    ResponseSchema(
        name='fact_3',
        description='Fact 3 about the topic'
    )
]


# Create parser from response schemas
parser = StructuredOutputParser.from_response_schemas(
    schema
)


template = PromptTemplate(

    template='Give 3 fact about {topic} \\n {format_instruction}',

    input_variables=['topic'],

    partial_variables={
        'format_instruction':
            parser.get_format_instructions()
    }
)


# Create chain
chain = template | model | parser


result = chain.invoke({
    'topic': 'black hole'
})


print(result)`}
        </CodeBlock>

        <p>
          Here, <strong>ResponseSchema</strong> defines the fields that the
          LLM should return.
        </p>
      </section>


      {/* PydanticOutputParser */}
      <section>
        <h3>4. PydanticOutputParser</h3>

        <p>
          <strong>PydanticOutputParser</strong> converts the LLM output into
          a Pydantic model. This is useful when we want structured data with
          type validation.
        </p>

        <CodeBlock language="python">
{`from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field

load_dotenv()


# Define the model
llm = HuggingFaceEndpoint(
    repo_id="google/gemma-2-2b-it",
    task="text-generation"
)


model = ChatHuggingFace(llm=llm)


# Define Pydantic model
class Person(BaseModel):

    name: str = Field(
        description='Name of the person'
    )

    age: int = Field(
        gt=18,
        description='Age of the person'
    )

    city: str = Field(
        description='Name of the city the person belongs to'
    )


# Create Pydantic parser
parser = PydanticOutputParser(
    pydantic_object=Person
)


template = PromptTemplate(

    template='''
    Generate the name, age and city of a fictional
    {place} person \\n {format_instruction}
    ''',

    input_variables=['place'],

    partial_variables={
        'format_instruction':
            parser.get_format_instructions()
    }
)


# Create chain
chain = template | model | parser


final_result = chain.invoke({
    'place': 'sri lankan'
})


print(final_result)`}
        </CodeBlock>

        <div className="note">
          <strong>Key Point:</strong> PydanticOutputParser is useful when
          you want the final output to follow a Pydantic model with defined
          field types and validation rules.
        </div>
      </section>


      {/* Comparison */}
      <section>
        <h2>Structured Output vs Output Parsers</h2>

        <table>
          <thead>
            <tr>
              <th>Method</th>
              <th>Purpose</th>
              <th>Best Used For</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td>TypedDict</td>
              <td>Defines dictionary structure using type hints</td>
              <td>Simple structured data</td>
            </tr>

            <tr>
              <td>Pydantic</td>
              <td>Defines and validates structured Python objects</td>
              <td>Type-safe applications</td>
            </tr>

            <tr>
              <td>JSON Schema</td>
              <td>Defines structure using JSON</td>
              <td>Multi-language applications</td>
            </tr>

            <tr>
              <td>StrOutputParser</td>
              <td>Returns output as a string</td>
              <td>Normal text output</td>
            </tr>

            <tr>
              <td>JSONOutputParser</td>
              <td>Parses output into JSON</td>
              <td>JSON-based applications</td>
            </tr>

            <tr>
              <td>StructuredOutputParser</td>
              <td>Uses predefined response fields</td>
              <td>Specific structured fields</td>
            </tr>

            <tr>
              <td>PydanticOutputParser</td>
              <td>Parses output into a Pydantic model</td>
              <td>Validated structured data</td>
            </tr>
          </tbody>
        </table>
      </section>


      {/* Summary */}
      <section>
        <h2>Summary</h2>

        <ul>
          <li>
            LLMs normally return free-form text, but applications often
            require structured data.
          </li>

          <li>
            Structured output makes LLM responses easier to parse, store,
            validate, and use.
          </li>

          <li>
            LangChain provides <strong>with_structured_output()</strong> for
            models that support structured output.
          </li>

          <li>
            TypedDict, Pydantic, and JSON Schema can be used to define the
            expected structure.
          </li>

          <li>
            Output Parsers can be used when direct structured output is not
            available.
          </li>

          <li>
            Important parsers include StrOutputParser, JSONOutputParser,
            StructuredOutputParser, and PydanticOutputParser.
          </li>
        </ul>
      </section>


      {/* Interview Questions */}
      <section>
        <h2>Most Asked Interview Questions</h2>

        <ol>
          <li>What is structured output in LangChain?</li>
          <li>Why do we need structured output from an LLM?</li>
          <li>What is the purpose of with_structured_output()?</li>
          <li>What is TypedDict?</li>
          <li>What is Pydantic?</li>
          <li>What is JSON Schema?</li>
          <li>What is an Output Parser?</li>
          <li>What is StrOutputParser?</li>
          <li>What is JSONOutputParser?</li>
          <li>What is StructuredOutputParser?</li>
          <li>What is PydanticOutputParser?</li>
          <li>What is the difference between Pydantic and PydanticOutputParser?</li>
          <li>When should we use with_structured_output()?</li>
          <li>When should we use Output Parsers?</li>
          <li>Why is structured output useful for AI agents?</li>
        </ol>
      </section>


      <PageNav
        prev={{
          label: 'Prompts   ',
          path: '/langchain/prompts'
        }}
        next={{
          label: 'Chains',
          path: '/langchain/chains'
        }}
      />

    </DocPage>
  );
}
